# Licensed to Apache Software Foundation (ASF) under one or more contributor
# license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright
# ownership. Apache Software Foundation (ASF) licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

apiVersion: operator.skywalking.apache.org/v1alpha1
kind: Fetcher
metadata:
  name: istio-prod-cluster
spec:
  type: ["prometheus"]
  OAPServerAddress: "default-oap:11800"
  clusterName: "istio-prod-cluster"

---
apiVersion: operator.skywalking.apache.org/v1alpha1
kind: OAPServer
metadata:
  name: default
spec:
  version: 9.1.0
  instances: 1
  image: apache/skywalking-oap-server:9.1.0
  config:
    - name: SW_OTEL_RECEIVER
      value: default
  service:
    template:
      type: ClusterIP

---
apiVersion: operator.skywalking.apache.org/v1alpha1
kind: UI
metadata:
  name: default
spec:
  version: 9.1.0
  instances: 1
  image: apache/skywalking-ui:9.1.0
  OAPServerAddress: default-oap:12800
  service:
    template:
      type: ClusterIP
    ingress:
      host: demo.ui.skywalking
