# Licensed to Apache Software Foundation (ASF) under one or more contributor
# license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright
# ownership. Apache Software Foundation (ASF) licenses this file to you under
# the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: satellite-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skywalking-system-satellite
  # Satellite count range limit
  minReplicas: 1
  maxReplicas: 3
  # Limit continuous scaling up
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Min
  metrics:
    # Average number of connections threshold
    - type: External
      external:
        metric:
          name: skywalking.apache.org|satellite_service_grpc_connect_count
          selector:
            matchLabels:
              "service.str.0": "satellite"
              "service.byte.1": "3a"
              "service.byte.2": "3a"
              "service.str.3": "satellite"
              "service.byte.4": "2d"
              "service.str.5": "service"
        target:
          type: Value
          value: 1900
    # Average CPU usage threshold
    - type: External
      external:
        metric:
          name: skywalking.apache.org|satellite_service_server_cpu_utilization
          selector:
            matchLabels:
              "service.str.0": "satellite"
              "service.byte.1": "3a"
              "service.byte.2": "3a"
              "service.str.3": "satellite"
              "service.byte.4": "2d"
              "service.str.5": "service"
        target:
          type: Value
          value: 75